const mongoose = require("mongoose");
const { Schema } = mongoose;

const userSchema = new Schema(
  {
    username: { type: String, required: true, unique: true },
    password: { type: String, required: true,select:false },
    email: { type: String, required: true, unique: true },
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
    phoneNumber: { type: String, required: true },
    role: {
      type: String,
      enum: ["admin", "site_coordiantor", "regional_manager"],
      required: true,
    },
    isVerified: { type: Boolean, default: false },
    verificationToken: { type: String },
    resetPasswordToken: { type: String },
    resetPasswordExpires: { type: Date },
  },
  {
    timestamps: true,
  }
);

const regionSchema = new Schema(
  {
    name: { type: String, required: true, unique: true },
    managerId: { type: Schema.Types.ObjectId, required: true, ref: "User" },
    sites: [{ type: Schema.Types.ObjectId, required: true, ref: "Site" }],
  },
  { timestamps: true }
);

const siteSchema = new Schema(
  {
    name: { type: String, required: true, unique: true },
    coordinatorId: { type: Schema.Types.ObjectId, ref: "User", required: true },
  },
  { timestamps: true }
);

const tokenSchema = new Schema(
  {
    userId: { type: String, required: true },
    token: { type: String, required: true },
    expireAt: { type: Date, expires: 60 * 60, default: Date.now },
  },
  { timestamps: true }
);

const formSchema = new Schema(
  {
    siteId: { type: String, required: true },
    dueDate: { type: Date, required: true },
    date: { type: Date, required: true },
    isPublished: { type: Boolean, default: false },
    indicators: {
      totalBloodDonations: { type: Number, default: null },
      familyReplacementDonations: { type: Number, default: null },
      firstTimeDonors: { type: Number, default: null },
      repeatDonors: { type: Number, default: null },
      studentDonors: { type: Number, default: null },
      governmentEmployeeDonors: { type: Number, default: null },
      privateEmployeeDonors: { type: Number, default: null },
      selfEmployedDonors: { type: Number, default: null },
      unemployedDonors: { type: Number, default: null },
      otherDonors: { type: Number, default: null },
      maleDonors: { type: Number, default: null },
      femaleDonors: { type: Number, default: null },
      under18Donors: { type: Number, default: null },
      age18To24Donors: { type: Number, default: null },
      age25To34Donors: { type: Number, default: null },
      age35To44Donors: { type: Number, default: null },
      age45To54Donors: { type: Number, default: null },
      age55To64Donors: { type: Number, default: null },
      over65Donors: { type: Number, default: null },
      apheresisDonations: { type: Number, default: null },
      donationsFromCenter: { type: Number, default: null },
      donationsFromMobile: { type: Number, default: null },
      mobileSessionsConducted: { type: Number, default: null },
      activeBloodDonorClubs: { type: Number, default: null },
      adrFainting: { type: Number, default: null },
      adrFaintingWithLossOfConsciousness: { type: Number, default: null },
      adrSeizure: { type: Number, default: null },
      adrTechnicalProblem: { type: Number, default: null },
      donorRefusals: { type: Number, default: null },
      otherAdrs: { type: Number, default: null },
      permanentDeferralsDueToTtis: { type: Number, default: null },
      deferralsByLowWeight: { type: Number, default: null },
      deferralsByAge: { type: Number, default: null },
      deferralsByPregnancyLactation: { type: Number, default: null },
      deferralsByBloodPressure: { type: Number, default: null },
      deferralsByLowHemoglobin: { type: Number, default: null },
      deferralsByOtherMedicalConditions: { type: Number, default: null },
      deferralsByHighRiskBehavior: { type: Number, default: null },
      deferralsByTravelHistory: { type: Number, default: null },
      deferralsByOtherReasons: { type: Number, default: null },
      postDonationCounsellingSystem: { type: Boolean, default: null },
      referralForPositiveTtisDonors: { type: Boolean, default: null },
      preDonationInformationGiven: { type: Number, default: null },
      preDonationCounselling: { type: Number, default: null },
      postDonationCounsellingService: { type: Number, default: null },
      postDonationCounsellingFromMobile: { type: Number, default: null },
      postDonationCounsellingFromCenter: { type: Number, default: null },
      nonReactiveDonorsReceivingPdc: { type: Number, default: null },
      reactiveDonorsReceivingPdc: { type: Number, default: null },
      referredReactiveDonorsReceivingPdc: { type: Number, default: null },
      donationsScreenedForTtis: { type: Number, default: null },
      samplesScreenedForTtis: { type: Number, default: null },
      samplesScreenedForBloodGroup: { type: Number, default: null },
      samplesScreenedForBloodGroupQualityAssured: {
        type: Number,
        default: null,
      },
      ttisPositive: { type: Number, default: null },
      hivPositive: { type: Number, default: null },
      hepatitisBPositive: { type: Number, default: null },
      hepatitisCPositive: { type: Number, default: null },
      syphilisPositive: { type: Number, default: null },
      donorsPositiveForTtis: { type: Number, default: null },
      componentProcessingSystem: { type: Boolean, default: null },
      wholeBloodSeparatedIntoComponents: { type: Number, default: null },
      crcUnitsPrepared: { type: Number, default: null },
      plateletsPrepared: { type: Number, default: null },
      ffpPrepared: { type: Number, default: null },
      cryoprecipitatePrepared: { type: Number, default: null },
      discardedUnitsOverweightCrc: { type: Number, default: null },
      discardedUnitsOverweightPlatelets: { type: Number, default: null },
      discardedUnitsOverweightFfp: { type: Number, default: null },
      discardedUnitsOverweightCryoprecipitate: { type: Number, default: null },
      discardedUnitsCollectionProblem: { type: Number, default: null },
      discardedUnitsExpired: { type: Number, default: null },
      discardedUnitsProcessingProblems: { type: Number, default: null },
      discardedUnitsReactiveTtis: { type: Number, default: null },
      discardedUnitsHemolyzed: { type: Number, default: null },
      discardedUnitsClotted: { type: Number, default: null },
      discardedUnitsStorageProblems: { type: Number, default: null },
      discardedUnitsTransportationProblems: { type: Number, default: null },
      discardedUnitsHighOd: { type: Number, default: null },
      discardedUnitsOthers: { type: Number, default: null },
      requestedAplusWbCrc: { type: Number, default: null },
      requestedBplusWbCrc: { type: Number, default: null },
      requestedAbplusWbCrc: { type: Number, default: null },
      requestedOplusWbCrc: { type: Number, default: null },
      requestedAminusWbCrc: { type: Number, default: null },
      requestedBminusWbCrc: { type: Number, default: null },
      requestedAbminusWbCrc: { type: Number, default: null },
      requestedOminusWbCrc: { type: Number, default: null },
      requestedFfpUnits: { type: Number, default: null },
      requestedPlateletsUnits: { type: Number, default: null },
      distributedAplusWbCrc: { type: Number, default: null },
      distributedBplusWbCrc: { type: Number, default: null },
      distributedAbplusWbCrc: { type: Number, default: null },
      distributedOplusWbCrc: { type: Number, default: null },
      distributedAminusWbCrc: { type: Number, default: null },
      distributedBminusWbCrc: { type: Number, default: null },
      distributedAbminusWbCrc: { type: Number, default: null },
      distributedOminusWbCrc: { type: Number, default: null },
      distributedFfpUnits: { type: Number, default: null },
      distributedPlateletsUnits: { type: Number, default: null },
      transferredAplusWbCrc: { type: Number, default: null },
      transferredBplusWbCrc: { type: Number, default: null },
      transferredAbplusWbCrc: { type: Number, default: null },
      transferredOplusWbCrc: { type: Number, default: null },
      transferredAminusWbCrc: { type: Number, default: null },
      transferredBminusWbCrc: { type: Number, default: null },
      transferredAbminusWbCrc: { type: Number, default: null },
      transferredOminusWbCrc: { type: Number, default: null },
      transferredFfpUnits: { type: Number, default: null },
      transferredPlateletsUnits: { type: Number, default: null },
      healthFacilitiesPerformingTransfusion: { type: Number, default: null },
      healthFacilitiesWithHtc: { type: Number, default: null },
      healthFacilitiesPerformingClinicalAudit: { type: Number, default: null },
      malePatientsTransfused: { type: Number, default: null },
      femalePatientsTransfused: { type: Number, default: null },
      patientsUnder5Transfused: { type: Number, default: null },
      patients5To14Transfused: { type: Number, default: null },
      patients15To44Transfused: { type: Number, default: null },
      patients45To59Transfused: { type: Number, default: null },
      patients60OrOlderTransfused: { type: Number, default: null },
      wholeBloodTransfused: { type: Number, default: null },
      redCellsTransfused: { type: Number, default: null },
      plateletsTransfused: { type: Number, default: null },
      ffpTransfused: { type: Number, default: null },
      cryoprecipitateTransfused: { type: Number, default: null },
      immunologicalHemolysisAboIncompatibility: { type: Number, default: null },
      suspectedHemolysisOtherAlloAntibody: { type: Number, default: null },
      nonImmunologicalHemolysis: { type: Number, default: null },
      postTransfusionPurpura: { type: Number, default: null },
      anaphylaxisHypersensitivity: { type: Number, default: null },
      transfusionRelatedLungInjury: { type: Number, default: null },
      graftVersusHostDisease: { type: Number, default: null },
      suspectedTransfusionAssociatedHiv: { type: Number, default: null },
      suspectedTransfusionAssociatedHbv: { type: Number, default: null },
      suspectedTransfusionAssociatedHcv: { type: Number, default: null },
      suspectedSepsisDonorUnit: { type: Number, default: null },
      suspectedTransfusionAssociatedMalaria: { type: Number, default: null },
      suspectedOtherParasiticInfection: { type: Number, default: null },
      transfusionAssociatedCirculatoryOverload: { type: Number, default: null },
      otherSeriousAtr: { type: Number, default: null },
      hivElisaKitsStock: { type: Number, default: null },
      hbvElisaKitsStock: { type: Number, default: null },
      hcvElisaKitsStock: { type: Number, default: null },
      syphilisElisaKitsStock: { type: Number, default: null },
      bloodBag350mlStock: { type: Number, default: null },
      bloodBag450mlSingleStock: { type: Number, default: null },
      bloodBag450mlTripleStock: { type: Number, default: null },
      transfusionSetStock: { type: Number, default: null },
      elisaKitsStockOutDays: { type: Number, default: null },
      bloodBagStockOutDays: { type: Number, default: null },
    },
  },
  { timestamps: true }
);

const User = mongoose.model("User", userSchema);
const Region = mongoose.model("Region", regionSchema);
const Site = mongoose.model("Site", siteSchema);
const Token = mongoose.model("Token", tokenSchema);
const Form = mongoose.model("Form", formSchema);

module.exports = {
  User,
  Region,
  Site,
  Token,
  Form,
};
